/* DictaMate 云端词库包 v1 —— 加载后写入 window.DICTA_CLOUD_INDEX */
window.DICTA_CLOUD_INDEX={name:"DictaMate 官方云端词库",updated:"2026-09-26",books:[
  {
    id: "news-basic", name: "新闻英语入门", tag: "新闻", desc: "看新闻必备的基础词：报道、采访、头条、评论",
    words: [
      ["headline","新闻标题","The headline caught my eye.","这个标题吸引了我的注意。"],
      ["article","文章","She wrote an article about the city.","她写了一篇关于这座城市的文章。"],
      ["report","报道","The report was on the front page.","这篇报道登上了头版。"],
      ["reporter","记者","The reporter asked many questions.","记者问了很多问题。"],
      ["journalist","记者；新闻工作者","He works as a journalist for a newspaper.","他在一家报社当记者。"],
      ["editor","编辑","The editor checked every word.","编辑检查了每一个字。"],
      ["interview","采访；访谈","She gave an interview on TV.","她在电视上接受了采访。"],
      ["source","消息来源","The source refused to be named.","消息来源不愿透露姓名。"],
      ["update","最新消息","Here is the latest update on the storm.","这是关于风暴的最新消息。"],
      ["breaking","突发的","We interrupt this program with breaking news.","我们中断节目插播突发新闻。"],
      ["coverage","报道；覆盖面","The event got wide media coverage.","这一事件得到了媒体的广泛报道。"],
      ["correspondent","驻外记者；通讯员","Our correspondent reports from Paris.","我们的记者在巴黎发来报道。"],
      ["press","新闻界；媒体","The press waited outside the court.","记者们等在法院外面。"],
      ["media","媒体","The media covered the story all week.","媒体整周都在报道这件事。"],
      ["bulletin","公告；简报","The news bulletin airs at noon.","午间播报新闻简报。"],
      ["anchor","新闻主播","The anchor opened the evening news.","主播开启了晚间新闻。"],
      ["story","报道；故事","This is a developing story.","这是一则正在发展的报道。"],
      ["column","专栏","He writes a weekly column about sports.","他每周写一篇体育专栏。"],
      ["commentary","评论；解说","The commentator gave live commentary.","解说员进行了现场解说。"],
      ["feature","特稿；专题","The magazine ran a feature on travel.","杂志刊登了一篇旅行专题。"],
      ["publish","发布；出版","The paper publishes daily at six.","这份报纸每天六点出版。"],
      ["circulation","发行量","The newspaper has a large circulation.","这份报纸发行量很大。"],
      ["edition","版本；版面","This is the morning edition.","这是早间版。"],
      ["issue","期号；议题","Climate is an important issue now.","气候现在是重要议题。"],
      ["subscriber","订阅者","The magazine has a million subscribers.","这本杂志有一百万订户。"],
      ["scoop","独家新闻","The young reporter got a big scoop.","这位年轻记者挖到了独家新闻。"],
      ["censorship","审查制度","Censorship limits what papers can print.","审查制度限制了报纸能刊登的内容。"],
      ["credibility","可信度","A good source keeps its credibility.","可靠的消息来源保持其可信度。"],
      ["rumor","谣言","The rumor spread quickly online.","谣言在网上迅速传播。"],
      ["fact","事实","Check the facts before you report.","报道前先核实事实。"],
      ["opinion","观点","His opinion differs from mine.","他的观点和我的不同。"],
      ["bias","偏见","Good journalism avoids bias.","好的新闻工作避免偏见。"],
      ["accuracy","准确性","Accuracy matters in every article.","准确性对每篇文章都很重要。"],
      ["objectivity","客观性","Reporters should keep objectivity.","记者应保持客观。"],
      ["briefing","简报会","The spokesman held a daily briefing.","发言人举行了每日简报会。"],
      ["presser","新闻发布会","The team held a presser after the match.","球队赛后举行了新闻发布会。"],
      ["leak","泄露","A leak revealed the secret plan.","一次泄密暴露了秘密计划。"],
      ["exclusive","独家消息","The channel aired an exclusive interview.","该频道播出了一段独家采访。"],
      ["deadline","截稿时间","The reporter met the deadline at midnight.","记者在午夜前赶上了截稿时间。"],
      ["dispatch","快讯；电讯","The dispatch arrived from the front line.","快讯从前线发来。"],
      ["agency","通讯社","The news agency broke the story first.","这家通讯社最先报道了此事。"],
      ["wire","通讯社电讯","The wire carried the news worldwide.","通讯社电讯把消息传向全球。"],
      ["freelancer","自由撰稿人","She works as a freelancer at home.","她在家做自由撰稿人。"],
      ["bylined","署名的","The bylined article won an award.","这篇署名文章获了奖。"],
      ["obituary","讣告","He wrote the obituary of his teacher.","他撰写了老师的讣告。"],
      ["supplement","增刊；副刊","The paper has a weekend supplement.","这份报纸有周末增刊。"],
      ["tabloid","小报","The tabloid loves celebrity gossip.","这家小报热衷名人八卦。"],
      ["broadsheet","大报","A broadsheet prints serious news.","大报刊登严肃新闻。"],
      ["magazine","杂志","She reads a fashion magazine monthly.","她每月读一本时尚杂志。"],
      ["readership","读者群","The column built a loyal readership.","这个专栏培养了忠实的读者群。"],
      ["subscription","订阅","A subscription costs fifty yuan a year.","订阅一年需要五十元。"],
      ["archive","档案；存档","Old issues are kept in the archive.","过期刊物存放在档案中。"],
      ["layout","版面设计","The layout of the page is clean.","这一版的版面很干净。"],
      ["caption","图片说明","The caption explains the photo.","图片说明解释了这张照片。"],
      ["plagiarism","抄袭","Plagiarism ends a journalist's career.","抄袭会毁掉记者的职业生涯。"],
      ["verify","核实","Reporters must verify every name.","记者必须核实每个名字。"],
      ["witness","目击者","A witness saw the whole accident.","一位目击者看到了整个事故。"],
      ["quote","引用；引语","The paper quoted the mayor directly.","报纸直接引用了市长的话。"],
      ["statement","声明","The office issued a short statement.","该部门发布了一份简短声明。"],
      ["announcement","通告","The announcement surprised everyone.","这则通告让所有人惊讶。"],
      ["ceremony","仪式","The opening ceremony was grand.","开幕式很盛大。"],
      ["conference","会议；发布会","The press conference lasted an hour.","新闻发布会持续了一个小时。"],
      ["seminar","研讨会","They held a seminar on education.","他们举办了一场教育研讨会。"],
      ["forum","论坛","The forum discussed public health.","论坛讨论了公共卫生。"]
    ]
  },
  {
    id: "news-politics", name: "时政新闻", tag: "时政", desc: "选举、议会、外交、制裁等政坛高频词",
    words: [
      ["government","政府","The government announced a new policy.","政府宣布了一项新政策。"],
      ["election","选举","The election takes place in May.","选举在五月举行。"],
      ["campaign","竞选活动","He ran a strong campaign.","他进行了一场强有力的竞选活动。"],
      ["candidate","候选人","The candidate promised lower taxes.","候选人承诺降低税收。"],
      ["vote","投票","Every citizen has the right to vote.","每位公民都有投票权。"],
      ["voter","选民","Voters lined up at the polling station.","选民们在投票站排起了队。"],
      ["parliament","议会","Parliament approved the new law.","议会批准了新法律。"],
      ["congress","国会","Congress debated the budget bill.","国会就预算法案进行了辩论。"],
      ["senate","参议院","The senate voted on the proposal.","参议院对该提案进行了表决。"],
      ["legislation","立法","New legislation protects workers' rights.","新立法保护工人权利。"],
      ["lawmaker","立法者","Lawmakers reached an agreement.","立法者们达成了协议。"],
      ["policy","政策","The policy takes effect next month.","这项政策下月生效。"],
      ["minister","部长；大臣","The minister met foreign guests.","部长会见了外国客人。"],
      ["cabinet","内阁","The cabinet discussed the crisis.","内阁讨论了这次危机。"],
      ["summit","峰会","Leaders met at the annual summit.","领导人在年度峰会上会面。"],
      ["diplomacy","外交","Diplomacy can prevent war.","外交可以阻止战争。"],
      ["ambassador","大使","The ambassador gave a speech.","大使发表了演讲。"],
      ["treaty","条约","The two countries signed a treaty.","两国签署了一项条约。"],
      ["sanction","制裁","Sanctions hurt the economy.","制裁损害了经济。"],
      ["protest","抗议","Thousands joined the protest.","数千人参加了抗议。"],
      ["reform","改革","Education reform is underway.","教育改革正在进行中。"],
      ["authority","当局；权威","The local authority issued a warning.","当地当局发布了警告。"],
      ["opposition","反对派","The opposition criticized the plan.","反对派批评了这项计划。"],
      ["coalition","联盟；联合政府","The coalition government took office.","联合政府宣誓就职。"],
      ["negotiation","谈判","Negotiation continued through the night.","谈判持续到深夜。"],
      ["ceasefire","停火","The two sides agreed to a ceasefire.","双方同意停火。"],
      ["constitution","宪法","The constitution guarantees freedom.","宪法保障自由。"],
      ["democracy","民主","Democracy needs an active public.","民主需要积极的公众。"],
      ["regime","政权","The old regime collapsed.","旧政权垮台了。"],
      ["sovereignty","主权","The nation defends its sovereignty.","国家捍卫自己的主权。"],
      ["territory","领土","The dispute is about territory.","争端涉及领土。"],
      ["alliance","同盟","The alliance strengthened trade ties.","同盟加强了贸易联系。"],
      ["refugee","难民","Refugees crossed the border at night.","难民在夜间越过边境。"],
      ["delegate","代表","Each country sent a delegate.","每个国家都派出了代表。"],
      ["spokesman","发言人","The spokesman answered reporters.","发言人回答了记者提问。"],
      ["impeachment","弹劾","Impeachment is a serious step.","弹劾是严肃的一步。"],
      ["referendum","公投","The referendum decided the issue.","公投决定了这个问题。"],
      ["resolution","决议","The UN passed a new resolution.","联合国通过了一项新决议。"],
      ["declaration","宣言","The declaration was signed by all.","宣言由所有人签署。"],
      ["agenda","议程","The economy topped the agenda.","经济是议程的首要议题。"],
      ["bill","法案","The bill passed by a small margin.","法案以微弱优势通过。"],
      ["term","任期","The president began a new term.","总统开始了新任期。"],
      ["debate","辩论","The debate lasted three hours.","辩论持续了三个小时。"],
      ["veto","否决","The president used his veto.","总统行使了否决权。"],
      ["electorate","选民群体","The electorate turned out in large numbers.","选民们大量参与投票。"],
      ["poll","民意调查","The poll shows a close race.","民调显示竞争激烈。"],
      ["landslide","压倒性胜利","She won the election by a landslide.","她以压倒性优势赢得选举。"],
      ["incumbent","现任者","The incumbent won again.","现任者再次获胜。"],
      ["opponent","对手","Her opponent conceded defeat.","她的对手承认败选。"],
      ["mandate","授权","The party claimed a clear mandate.","该党声称获得了明确授权。"],
      ["ratify","批准","The senate ratified the treaty.","参议院批准了条约。"],
      ["amend","修改；修正","They amended the law last year.","他们去年修订了法律。"],
      ["withdraw","撤回；退出","The country decided to withdraw.","该国决定退出。"],
      ["enforce","执行","Police enforce the new rules.","警方执行新规定。"],
      ["oversee","监督","A committee oversees the process.","一个委员会监督该过程。"],
      ["comply","遵守","All sides must comply with the deal.","各方必须遵守协议。"],
      ["uphold","维护；支持","The court upheld the decision.","法院维持了原判。"],
      ["grant","授予","The king granted them land.","国王赐予他们土地。"],
      ["pledge","承诺","They pledged to cut emissions.","他们承诺减少排放。"],
      ["draft","草案","The draft is open for comments.","草案公开征求意见。"],
      ["clause","条款","The clause protects small firms.","该条款保护小企业。"],
      ["tension","紧张局势","Tension rose along the border.","边境紧张局势升级。"],
      ["escalate","升级","The conflict began to escalate.","冲突开始升级。"],
      ["mediate","调解","A neutral country helped mediate.","一个中立国帮助调解。"],
      ["boycott","抵制","They called for a boycott of the event.","他们呼吁抵制该活动。"]
    ]
  },
  {
    id: "news-economy", name: "财经新闻", tag: "财经", desc: "经济、股市、汇率、关税等金融报道高频词",
    words: [
      ["economy","经济","The economy grew by three percent.","经济增长了百分之三。"],
      ["inflation","通货膨胀","Inflation pushed prices higher.","通货膨胀推高了物价。"],
      ["recession","经济衰退","The recession lasted two years.","经济衰退持续了两年。"],
      ["growth","增长","The country saw steady growth.","这个国家实现了稳定增长。"],
      ["market","市场","The stock market closed higher.","股市收涨。"],
      ["stock","股票","He bought stocks in the tech firm.","他买了这家科技公司的股票。"],
      ["share","股份","She owns a share of the company.","她拥有公司的一份股份。"],
      ["bond","债券","The government sold new bonds.","政府发行了新债券。"],
      ["fund","基金","The fund invests in green energy.","该基金投资绿色能源。"],
      ["interest","利息；利率","Interest rates remain low.","利率保持低位。"],
      ["rate","比率；费率","The exchange rate changed overnight.","汇率一夜之间发生了变化。"],
      ["currency","货币","The currency lost value.","该货币贬值了。"],
      ["exchange","汇率；兑换","I need to exchange some money.","我需要兑换一些钱。"],
      ["trade","贸易","Trade between the nations grew.","两国之间的贸易增长了。"],
      ["tariff","关税","A new tariff raised import costs.","新关税提高了进口成本。"],
      ["export","出口","Cars are a major export.","汽车是主要出口产品。"],
      ["import","进口","The country depends on oil imports.","该国依赖石油进口。"],
      ["revenue","收入；税收","Ticket revenue doubled this year.","今年门票收入翻了一番。"],
      ["profit","利润","The firm reported a record profit.","这家公司报告了创纪录的利润。"],
      ["loss","亏损","The store closed after a big loss.","这家店在大幅亏损后关门了。"],
      ["investment","投资","Education is a long-term investment.","教育是长期投资。"],
      ["investor","投资者","Investors welcomed the news.","投资者对此消息表示欢迎。"],
      ["shareholder","股东","Shareholders approved the deal.","股东批准了这笔交易。"],
      ["merger","并购","The merger created a giant company.","这次并购造就了一家巨头公司。"],
      ["acquisition","收购","The acquisition cost two billion.","这次收购花费了二十亿。"],
      ["bankruptcy","破产","The airline filed for bankruptcy.","该航空公司申请破产。"],
      ["deficit","赤字","The budget deficit shrank.","预算赤字缩小了。"],
      ["surplus","盈余","The country enjoys a trade surplus.","该国享有贸易顺差。"],
      ["budget","预算","The budget was approved in March.","预算于三月获得批准。"],
      ["debt","债务","The country's debt keeps growing.","这个国家的债务持续增长。"],
      ["subsidy","补贴","Farmers receive a grain subsidy.","农民获得粮食补贴。"],
      ["monopoly","垄断","The company has a monopoly in telecom.","这家公司垄断了电信业。"],
      ["competition","竞争","Competition benefits consumers.","竞争有利于消费者。"],
      ["consumption","消费","Domestic consumption is rising.","国内消费正在上升。"],
      ["manufacturing","制造业","Manufacturing employs many workers.","制造业雇用了许多工人。"],
      ["industry","产业；工业","The tourism industry is booming.","旅游业正在蓬勃发展。"],
      ["employment","就业","Full employment is the goal.","充分就业是目标。"],
      ["unemployment","失业","Unemployment fell to a low level.","失业率降至低点。"],
      ["wage","工资","Workers demanded higher wages.","工人们要求提高工资。"],
      ["price","价格","Oil prices jumped sharply.","油价大幅上涨。"],
      ["demand","需求","Demand for housing remains strong.","住房需求依然强劲。"],
      ["supply","供应","Supply cannot keep up with demand.","供应跟不上需求。"],
      ["forecast","预测","The forecast predicts slow growth.","预测认为增长将放缓。"],
      ["index","指数","The price index rose slightly.","物价指数略有上升。"],
      ["dividend","股息","The company pays a yearly dividend.","该公司每年派发股息。"],
      ["stimulus","刺激措施","The government launched a stimulus plan.","政府启动了刺激计划。"],
      ["bailout","救助；纾困","Banks received a government bailout.","银行获得了政府救助。"],
      ["inventory","库存","The store has high inventory now.","这家店现在库存很高。"],
      ["turnover","营业额；周转","Annual turnover hit a new high.","年营业额创下新高。"],
      ["asset","资产","The firm sold its main asset.","该公司出售了主要资产。"],
      ["liability","负债","The debt is a heavy liability.","这笔债务是沉重的负债。"],
      ["mortgage","抵押贷款","They took a mortgage on the house.","他们用房子办了抵押贷款。"],
      ["credit","信贷；信用","The bank extended more credit.","银行增加了信贷。"],
      ["debtor","债务人","The debtor promised to repay.","债务人承诺偿还。"],
      ["creditor","债权人","Creditors agreed to delay payment.","债权人同意延期付款。"],
      ["fluctuate","波动","Prices fluctuate with demand.","价格随需求波动。"],
      ["plunge","暴跌","The shares plunged after the news.","消息公布后股价暴跌。"],
      ["rally","回升","Stocks rallied at the close.","股市在收盘时回升。"],
      ["downturn","下行；衰退","The downturn hit small shops.","经济下行打击了小商店。"],
      ["boom","繁荣","The city enjoyed a building boom.","这座城市经历了建筑热潮。"],
      ["slump","萧条","Sales went into a slump.","销售陷入低迷。"],
      ["retail","零售","Retail sales rose in December.","十二月零售额上升。"],
      ["wholesale","批发","The goods are sold wholesale.","这些货物是批发出售的。"],
      ["auction","拍卖","The painting sold at auction.","这幅画在拍卖会上售出。"],
      ["bidding","投标；竞价","The bidding started at one million.","竞标从一百万开始。"]
    ]
  },
  {
    id: "news-tech", name: "科技新闻", tag: "科技", desc: "人工智能、芯片、网络、航天等科技报道词汇",
    words: [
      ["technology","技术","New technology changes our lives.","新技术改变我们的生活。"],
      ["innovation","创新","Innovation drives the company forward.","创新推动公司前进。"],
      ["startup","初创公司","The startup raised five million.","这家初创公司融资五百万。"],
      ["software","软件","The software needs an update.","这款软件需要更新。"],
      ["hardware","硬件","The hardware is cheap but strong.","这款硬件便宜又结实。"],
      ["algorithm","算法","The algorithm learns from data.","该算法从数据中学习。"],
      ["intelligence","智能；情报","Artificial intelligence is advancing fast.","人工智能发展迅速。"],
      ["platform","平台","The app runs on every platform.","这个应用在所有平台上运行。"],
      ["device","设备","Keep your device charged.","保持设备电量充足。"],
      ["network","网络","The network covers the whole city.","网络覆盖全城。"],
      ["cybersecurity","网络安全","Cybersecurity protects our data.","网络安全保护我们的数据。"],
      ["data","数据","The survey collected useful data.","调查收集了有用的数据。"],
      ["database","数据库","The database holds millions of records.","数据库存有数百万条记录。"],
      ["research","研究","The lab does cancer research.","该实验室从事癌症研究。"],
      ["scientist","科学家","The scientist won a major prize.","这位科学家获得了重要奖项。"],
      ["breakthrough","突破","The cure was a medical breakthrough.","这种疗法是医学突破。"],
      ["prototype","原型","They tested a working prototype.","他们测试了一个可用的原型。"],
      ["patent","专利","The company holds the patent.","这家公司拥有这项专利。"],
      ["launch","发布；发射","The rocket launch was successful.","火箭发射成功。"],
      ["version","版本","Download the latest version.","下载最新版本。"],
      ["update","更新","The update fixed several bugs.","这次更新修复了几个漏洞。"],
      ["bug","漏洞；故障","They found a bug in the code.","他们在代码中发现了一个漏洞。"],
      ["server","服务器","The server went down at noon.","服务器在中午宕机了。"],
      ["cloud","云","Photos are saved in the cloud.","照片保存在云端。"],
      ["encryption","加密","Encryption keeps messages secret.","加密保证消息保密。"],
      ["privacy","隐私","The app respects your privacy.","这个应用尊重你的隐私。"],
      ["security","安全","Security is our top concern.","安全是我们最关心的问题。"],
      ["surveillance","监控","Street cameras provide surveillance.","街边摄像头提供监控。"],
      ["automation","自动化","Automation saves time and money.","自动化省时又省钱。"],
      ["robotics","机器人技术","Robotics is changing factories.","机器人技术正在改变工厂。"],
      ["chip","芯片","The chip runs faster than ever.","这款芯片运行比以前更快。"],
      ["semiconductor","半导体","Semiconductors power modern devices.","半导体为现代设备提供动力。"],
      ["battery","电池","The battery lasts all day.","这块电池能用一整天。"],
      ["electric","电动的","The electric car is quiet.","这辆电动车很安静。"],
      ["renewable","可再生的","Solar power is a renewable source.","太阳能是可再生能源。"],
      ["satellite","卫星","The satellite maps the ocean.","这颗卫星绘制海洋地图。"],
      ["drone","无人机","The drone filmed the whole valley.","无人机拍摄了整个山谷。"],
      ["virtual","虚拟的","They met in a virtual room.","他们在虚拟房间里见面。"],
      ["digital","数字的","The library went digital.","图书馆实现了数字化。"],
      ["download","下载","You can download the file free.","你可以免费下载这个文件。"],
      ["upload","上传","She uploaded the video online.","她把视频上传到了网上。"],
      ["browser","浏览器","Open the link in your browser.","在浏览器中打开这个链接。"],
      ["application","应用程序","The application works offline too.","这个应用离线也能用。"],
      ["interface","界面","The interface is easy to use.","这个界面很容易使用。"],
      ["sensor","传感器","The sensor detects motion.","传感器检测运动。"],
      ["quantum","量子","Quantum computing is still new.","量子计算仍处于早期。"],
      ["artificial","人造的","The lake is artificial.","这个湖是人造的。"],
      ["neural","神经的","Neural networks power the model.","神经网络驱动这个模型。"],
      ["deep","深度的","The model uses deep learning.","该模型使用深度学习。"],
      ["frontier","前沿","They work at the frontier of science.","他们工作在科学前沿。"],
      ["compute","计算","Cloud compute scales on demand.","云端计算按需扩展。"],
      ["storage","存储","Storage space is running low.","存储空间快用完了。"],
      ["streaming","流媒体","Streaming replaced the DVD player.","流媒体取代了 DVD 播放器。"],
      ["gadget","小设备","This gadget tracks your steps.","这个小设备记录你的步数。"],
      ["wearable","可穿戴的","Wearable devices monitor health.","可穿戴设备监测健康。"],
      ["immersive","沉浸式的","The game offers an immersive world.","这款游戏提供了沉浸式的世界。"],
      ["augmented","增强的","Augmented reality overlays the real world.","增强现实叠加在真实世界上。"],
      ["wireless","无线的","The wireless charger is convenient.","无线充电器很方便。"],
      ["connectivity","连接性","Good connectivity matters in remote areas.","在偏远地区良好的连接性很重要。"],
      ["bandwidth","带宽","Video calls need high bandwidth.","视频通话需要高带宽。"],
      ["latency","延迟","Low latency is key for gaming.","低延迟对游戏至关重要。"],
      ["hacker","黑客","A hacker tried to break in.","一名黑客试图入侵。"],
      ["malware","恶意软件","The malware was removed quickly.","恶意软件被迅速清除。"],
      ["firewall","防火墙","The firewall blocks suspicious traffic.","防火墙拦截可疑流量。"],
      ["credential","凭证","Keep your credentials safe.","保管好你的登录凭证。"]
    ]
  },
  {
    id: "news-sports", name: "体育新闻", tag: "体育", desc: "赛事、冠军、转会、伤病等体坛报道常用词",
    words: [
      ["athlete","运动员","The athlete trains six hours a day.","这位运动员每天训练六小时。"],
      ["championship","锦标赛；冠军","They won the world championship.","他们赢得了世界锦标赛。"],
      ["tournament","锦标赛；联赛","The tournament starts on Friday.","锦标赛周五开始。"],
      ["match","比赛","The match ended in a draw.","比赛以平局结束。"],
      ["league","联赛","The team leads the league.","这支球队领跑联赛。"],
      ["score","得分","The final score was three to one.","最终比分是三比一。"],
      ["victory","胜利","The victory thrilled the fans.","这场胜利让球迷们激动不已。"],
      ["defeat","失利","It was a painful defeat.","这是一场痛苦的失利。"],
      ["final","决赛","They reached the final again.","他们再次进入决赛。"],
      ["coach","教练","The coach changed the lineup.","教练调整了阵容。"],
      ["referee","裁判","The referee blew the whistle.","裁判吹响了哨子。"],
      ["stadium","体育场","The stadium holds eighty thousand fans.","体育场能容纳八万名球迷。"],
      ["record","纪录","She broke the national record.","她打破了全国纪录。"],
      ["medal","奖牌","He won a gold medal.","他赢得了一枚金牌。"],
      ["gold","金牌","The team is aiming for gold.","这支队伍志在夺金。"],
      ["silver","银牌","She took the silver in diving.","她获得了跳水银牌。"],
      ["bronze","铜牌","They won the bronze medal.","他们获得了铜牌。"],
      ["qualify","晋级；取得资格","The team qualified for the final.","这支球队晋级决赛。"],
      ["qualifier","预选赛","They won the qualifier easily.","他们轻松赢得预选赛。"],
      ["knockout","淘汰赛","It was a knockout stage match.","这是一场淘汰赛阶段的比赛。"],
      ["semifinal","半决赛","The semifinal was tense.","半决赛气氛紧张。"],
      ["quarterfinal","四分之一决赛","They lost in the quarterfinal.","他们在四分之一决赛中失利。"],
      ["penalty","点球；罚球","The penalty decided the game.","这个点球决定了比赛。"],
      ["overtime","加时赛","The game went into overtime.","比赛进入加时赛。"],
      ["goal","进球","His goal sealed the win.","他的进球锁定了胜局。"],
      ["goalkeeper","守门员","The goalkeeper made a great save.","守门员做出了一次精彩扑救。"],
      ["defender","后卫","The defender cleared the ball.","后卫解围了。"],
      ["midfielder","中场","The midfielder controls the tempo.","这名中场控制着节奏。"],
      ["striker","前锋","The striker scored twice.","这名前锋进了两个球。"],
      ["captain","队长","The captain lifted the trophy.","队长举起了奖杯。"],
      ["substitute","替补","The substitute scored the winner.","替补打进了制胜球。"],
      ["squad","阵容","The squad has fresh players.","阵容中有新球员。"],
      ["lineup","首发阵容","The lineup was announced early.","首发阵容提前公布。"],
      ["fitness","体能","Fitness is the key to endurance.","体能是耐力的关键。"],
      ["injury","伤病","The injury kept him out for weeks.","伤病让他缺席数周。"],
      ["suspension","停赛","He faced a two-game suspension.","他面临两场停赛。"],
      ["transfer","转会","The transfer fee broke records.","转会费打破了纪录。"],
      ["sponsor","赞助商","The sponsor put its logo on the shirts.","赞助商把标志印在了球衣上。"],
      ["venue","赛场；场馆","The venue was packed.","赛场座无虚席。"],
      ["ticket","门票","Tickets sold out in an hour.","门票一小时内售罄。"],
      ["fan","球迷","The fans sang all night.","球迷们整晚都在歌唱。"],
      ["spectator","观众","Spectators cheered loudly.","观众们大声欢呼。"],
      ["trophy","奖杯","They brought the trophy home.","他们把奖杯带回了家。"],
      ["runner-up","亚军","She finished as runner-up.","她获得了亚军。"],
      ["hat-trick","帽子戏法","He scored a hat-trick.","他上演了帽子戏法。"],
      ["underdog","弱势一方","The underdog shocked everyone.","弱旅震惊了所有人。"],
      ["favorite","夺冠热门","The favorite lost early.","夺冠热门早早出局。"],
      ["upset","爆冷","The result was a huge upset.","这个结果是一次大爆冷。"],
      ["comeback","逆转；回归","They staged a great comeback.","他们上演了精彩的逆转。"],
      ["drought","低迷期","The club ended its title drought.","俱乐部结束了冠军荒。"],
      ["streak","连胜；连败","Their winning streak reached ten.","他们的连胜达到十场。"],
      ["rank","排名","She is ranked second in the world.","她世界排名第二。"],
      ["seed","种子选手","The top seed advanced easily.","头号种子轻松晋级。"],
      ["draft","选秀","He was the first pick in the draft.","他是选秀的状元。"],
      ["contract","合同","The star signed a new contract.","这位球星签了新合同。"],
      ["agent","经纪人","His agent negotiated the deal.","他的经纪人谈判了这笔交易。"],
      ["stamina","耐力","Long races test your stamina.","长跑考验耐力。"],
      ["agility","敏捷","The player is known for agility.","这位球员以敏捷著称。"],
      ["tactics","战术","The coach changed tactics at half-time.","教练在中场时改变了战术。"],
      ["strategy","战略","Strategy wins games, not luck.","赢得比赛靠战略而不是运气。"],
      ["discipline","纪律","Discipline builds a strong team.","纪律造就强大的团队。"],
      ["sportsmanship","体育精神","Fair play is good sportsmanship.","公平竞争是良好的体育精神。"]
    ]
  },
{
    id: "news-entertainment", name: "娱乐文化新闻", tag: "娱乐", desc: "影视、音乐、票房、明星等文娱报道词汇",
    words: [
      ["celebrity","名人","The celebrity waved to the crowd.","名人向人群挥手。"],
      ["premiere","首映","The premiere drew many stars.","首映礼吸引了许多明星。"],
      ["festival","电影节；音乐节","The film festival opens tonight.","电影节今晚开幕。"],
      ["album","专辑","Her new album tops the charts.","她的新专辑登上榜首。"],
      ["concert","演唱会","The concert was sold out.","演唱会的门票售罄。"],
      ["award","奖项","The film won three awards.","这部电影赢得三项大奖。"],
      ["nominee","提名者","The nominees were announced today.","今天公布了提名名单。"],
      ["nomination","提名","The movie received ten nominations.","这部电影获得十项提名。"],
      ["director","导演","The director shot the scene in one take.","导演一条就拍完了这个镜头。"],
      ["producer","制片人","The producer backed the project.","制片人资助了这个项目。"],
      ["actor","演员","The actor prepared for months.","这位演员准备了几个月。"],
      ["actress","女演员","The actress won best lead.","这位女演员获得最佳女主角。"],
      ["audience","观众","The audience laughed throughout.","观众从头笑到尾。"],
      ["tour","巡演","The band begins a world tour.","乐队开始世界巡演。"],
      ["release","发布；上映","The movie releases on Friday.","这部电影周五上映。"],
      ["trailer","预告片","The trailer looks amazing.","预告片看起来棒极了。"],
      ["soundtrack","原声带","The soundtrack became a hit.","原声带成了热门。"],
      ["drama","电视剧；戏剧","The drama aired every Sunday.","这部电视剧每周日播出。"],
      ["series","剧集","The series has three seasons.","这部剧集有三季。"],
      ["episode","集","The final episode surprised us.","大结局让我们意外。"],
      ["script","剧本","The script took two years to write.","剧本花了两年写成。"],
      ["screenplay","电影剧本","He adapted the novel into a screenplay.","他把小说改编成电影剧本。"],
      ["cast","演员阵容","The cast is full of talent.","演员阵容人才济济。"],
      ["plot","情节","The plot twists at the end.","情节在结尾处反转。"],
      ["sequel","续集","The sequel is even better.","续集更好看。"],
      ["franchise","系列电影","The franchise spans twenty years.","这个系列电影跨度二十年。"],
      ["hit","热门作品","The show was a huge hit.","这部剧大受欢迎。"],
      ["blockbuster","大片","The blockbuster broke box office records.","这部大片打破了票房纪录。"],
      ["masterpiece","杰作","Critics call it a masterpiece.","评论家称它为杰作。"],
      ["genre","类型","Science fiction is my favorite genre.","科幻是我最喜欢的类型。"],
      ["comedy","喜剧","The comedy made everyone laugh.","这部喜剧让所有人发笑。"],
      ["documentary","纪录片","The documentary shows real life at sea.","这部纪录片展示了真实的海上生活。"],
      ["animation","动画","The animation is beautiful to watch.","这部动画看起来很精美。"],
      ["cinema","电影院","We met at the cinema.","我们在电影院见面。"],
      ["screening","放映","There is a midnight screening tonight.","今晚有一场午夜放映。"],
      ["review","影评；评论","The review praised the acting.","影评称赞了表演。"],
      ["critic","评论家","The critics loved the ending.","评论家们喜欢这个结局。"],
      ["gossip","八卦","The magazine is full of gossip.","这本杂志满是八卦。"],
      ["paparazzi","狗仔队","The paparazzi followed the star.","狗仔队跟着那位明星。"],
      ["fame","名声","Fame came with a price.","名声是有代价的。"],
      ["scandal","丑闻","The scandal ended his career.","丑闻终结了他的事业。"],
      ["endorsement","代言","She signed an endorsement deal.","她签了一份代言合同。"],
      ["viral","病毒式传播的","The video went viral online.","这个视频在网上爆火。"],
      ["trend","潮流","Short videos are the current trend.","短视频是当下的潮流。"],
      ["streaming","流媒体","Streaming changed how we watch shows.","流媒体改变了我们看剧的方式。"],
      ["teaser","预告片段","The studio dropped a new teaser.","制片方放出了新预告。"],
      ["set","片场；布景","The set looks like a real street.","布景看起来像一条真实的街道。"],
      ["rehearsal","排练","The rehearsal ran late into the night.","排练一直进行到深夜。"],
      ["comeback","复出","Her comeback amazed the fans.","她的复出让粉丝惊叹。"],
      ["debut","首次亮相","The singer made her debut at eighteen.","这位歌手十八岁首次亮相。"],
      ["recording","录音","The recording took one week.","录音花了一周时间。"],
      ["playlist","播放列表","Add this song to your playlist.","把这首歌加进你的播放列表。"],
      ["audition","试镜；试音","He passed the audition easily.","他轻松通过了试镜。"],
      ["choreography","编舞","The choreography was brilliant.","编舞非常出色。"],
      ["screenwriter","编剧","The screenwriter won an award.","这位编剧获奖了。"],
      ["boxoffice","票房","The film's boxoffice broke records.","这部电影的票房打破了纪录。"],
      ["popstar","流行明星","The popstar filled the arena.","这位流行明星坐满了体育馆。"],
      ["idol","偶像","Teens admire their idols.","青少年崇拜他们的偶像。"],
      ["reality","真人秀","The reality show aired its finale.","真人秀播出了大结局。"],
      ["variety","综艺节目","The variety show is light and fun.","这档综艺轻松有趣。"]
    ]
  },
  {
    id: "news-health", name: "健康医疗新闻", tag: "健康", desc: "疫情、疫苗、治疗、公共卫生等报道高频词",
    words: [
      ["health","健康","Sleep is vital for health.","睡眠对健康至关重要。"],
      ["hospital","医院","The hospital treats thousands daily.","这家医院每天诊治数千人。"],
      ["clinic","诊所","The clinic opens on weekends.","诊所周末也营业。"],
      ["patient","病人","The patient is recovering well.","病人恢复得很好。"],
      ["doctor","医生","The doctor prescribed some rest.","医生建议休息。"],
      ["surgeon","外科医生","The surgeon performed the operation.","外科医生做了手术。"],
      ["nurse","护士","The nurse checked my temperature.","护士给我量了体温。"],
      ["treatment","治疗","Treatment began immediately.","治疗立即开始。"],
      ["therapy","疗法","Physical therapy helped his knee.","物理疗法对他的膝盖有帮助。"],
      ["vaccine","疫苗","The vaccine prevents the disease.","疫苗预防这种疾病。"],
      ["disease","疾病","Heart disease is common here.","心脏病在这里很常见。"],
      ["symptom","症状","A fever is a common symptom.","发烧是常见症状。"],
      ["diagnosis","诊断","Early diagnosis saves lives.","早期诊断能挽救生命。"],
      ["medicine","药物；医学","Take the medicine after meals.","饭后服药。"],
      ["drug","药品","The new drug passed trials.","新药通过了试验。"],
      ["prescription","处方","The prescription is ready at the pharmacy.","处方已备好，在药房可取。"],
      ["outbreak","爆发","The outbreak was contained quickly.","疫情很快得到控制。"],
      ["epidemic","流行病","The epidemic spread across regions.","流行病在多个地区蔓延。"],
      ["pandemic","大流行","The pandemic changed daily life.","大流行改变了日常生活。"],
      ["infection","感染","The infection cleared in a week.","感染一周内痊愈。"],
      ["immunity","免疫力","Good sleep builds immunity.","好的睡眠增强免疫力。"],
      ["prevention","预防","Prevention is better than cure.","预防胜于治疗。"],
      ["nutrition","营养","Good nutrition supports growth.","良好的营养支持成长。"],
      ["diet","饮食","A balanced diet keeps you fit.","均衡饮食让你保持健康。"],
      ["obesity","肥胖","Obesity raises health risks.","肥胖增加健康风险。"],
      ["diabetes","糖尿病","Diabetes needs daily care.","糖尿病需要日常护理。"],
      ["cancer","癌症","Early checks can catch cancer.","早期检查能发现癌症。"],
      ["heart","心脏","Exercise strengthens the heart.","锻炼能强健心脏。"],
      ["stroke","中风","A stroke needs fast care.","中风需要快速救治。"],
      ["depression","抑郁症","Depression is treatable with support.","抑郁症在支持下是可以治疗的。"],
      ["anxiety","焦虑","Deep breaths reduce anxiety.","深呼吸能缓解焦虑。"],
      ["mental","精神的","Mental health matters as much as physical.","心理健康和身体健康同样重要。"],
      ["wellness","健康；保健","The spa focuses on wellness.","这家水疗中心专注于健康养生。"],
      ["hygiene","卫生","Wash hands for good hygiene.","勤洗手保持卫生。"],
      ["sanitation","公共卫生","Clean water and sanitation save lives.","清洁饮水和公共卫生能挽救生命。"],
      ["quarantine","隔离","The traveler stayed in quarantine.","这名旅客接受了隔离。"],
      ["lockdown","封锁","The city entered a strict lockdown.","这座城市进入严格封锁。"],
      ["screening","筛查","Free screening is offered yearly.","每年提供免费筛查。"],
      ["transplant","移植","The transplant surgery succeeded.","移植手术成功了。"],
      ["surgery","手术","The surgery lasted five hours.","手术持续了五个小时。"],
      ["complication","并发症","No complication followed the surgery.","手术后没有并发症。"],
      ["recovery","康复","Full recovery takes time.","完全康复需要时间。"],
      ["lifespan","寿命","Healthy habits lengthen lifespan.","健康习惯能延长寿命。"],
      ["mortality","死亡率","The mortality rate fell sharply.","死亡率大幅下降。"],
      ["chronic","慢性的","Asthma is a chronic condition.","哮喘是一种慢性疾病。"],
      ["acute","急性的","He was taken in with acute pain.","他因剧痛被送进医院。"],
      ["infectious","传染的","Measles is highly infectious.","麻疹传染性很强。"],
      ["contagious","接触传染的","The flu is contagious.","流感具有接触传染性。"],
      ["asymptomatic","无症状的","An asymptomatic case is still risky.","无症状病例仍有风险。"],
      ["antibody","抗体","Antibodies fight the virus.","抗体对抗病毒。"],
      ["antiviral","抗病毒的","Doctors gave an antiviral drug.","医生给了一种抗病毒药物。"],
      ["dosage","剂量","Follow the dosage on the label.","按照标签上的剂量服用。"],
      ["side-effect","副作用","The drug has a mild side-effect.","这种药有轻微的副作用。"],
      ["overdose","过量","An overdose can be fatal.","过量服用可能致命。"],
      ["addiction","成瘾","Addiction needs professional help.","成瘾需要专业帮助。"],
      ["rehabilitation","康复治疗","He completed six months of rehabilitation.","他完成了六个月的康复治疗。"],
      ["first-aid","急救","She learned first-aid skills.","她学会了急救技能。"],
      ["emergency","急诊；紧急情况","Call the emergency number at once.","立即拨打急救电话。"],
      ["intensive","重症监护的","The patient moved to intensive care.","病人转入重症监护。"],
      ["clinical","临床的","The drug entered clinical trials.","该药物进入临床试验。"],
      ["genetic","基因的","Genetic tests reveal risks.","基因检测揭示风险。"]
    ]
  },
  {
    id: "news-environment", name: "环境气候新闻", tag: "环境", desc: "气候、排放、极端天气、生态保护等报道词汇",
    words: [
      ["environment","环境","We must protect the environment.","我们必须保护环境。"],
      ["climate","气候","The climate is warming worldwide.","全球气候正在变暖。"],
      ["pollution","污染","Air pollution affects every city.","空气污染影响每一座城市。"],
      ["emission","排放","Factories cut their emissions.","工厂减少了排放。"],
      ["carbon","碳","Carbon levels keep rising.","碳含量持续上升。"],
      ["renewable","可再生的","Wind is a renewable resource.","风是可再生资源。"],
      ["sustainable","可持续的","We need sustainable farming.","我们需要可持续农业。"],
      ["ecosystem","生态系统","The reef is a fragile ecosystem.","珊瑚礁是脆弱的生态系统。"],
      ["biodiversity","生物多样性","Forests protect biodiversity.","森林保护生物多样性。"],
      ["conservation","保护；节约","Water conservation is essential.","节约用水至关重要。"],
      ["drought","干旱","The drought ruined the harvest.","干旱毁了收成。"],
      ["flood","洪水","The flood forced people to leave.","洪水迫使人们撤离。"],
      ["wildfire","野火","The wildfire spread for miles.","野火蔓延数英里。"],
      ["glacier","冰川","The glacier is melting fast.","冰川正在快速融化。"],
      ["recycling","回收利用","Recycling reduces waste.","回收利用减少垃圾。"],
      ["landfill","垃圾填埋场","The landfill is nearly full.","垃圾填埋场快满了。"],
      ["deforestation","滥伐森林","Deforestation harms wildlife.","滥伐森林危害野生动物。"],
      ["extinction","灭绝","The species faces extinction.","这个物种面临灭绝。"],
      ["species","物种","Many species live in this forest.","这片森林里生活着许多物种。"],
      ["habitat","栖息地","The wetland is their habitat.","湿地是它们的栖息地。"],
      ["wildlife","野生动物","Wildlife needs safe corridors.","野生动物需要安全的通道。"],
      ["greenhouse","温室","Greenhouse gases trap heat.","温室气体锁住热量。"],
      ["warming","变暖","Global warming raises sea levels.","全球变暖抬升海平面。"],
      ["energy","能源","Save energy at home.","在家节约能源。"],
      ["solar","太阳能的","Solar panels cover the roof.","屋顶铺满了太阳能板。"],
      ["tidal","潮汐的","Tidal energy comes from the sea.","潮汐能来自大海。"],
      ["fossil","化石","Fossil fuels are running out.","化石燃料正在枯竭。"],
      ["fuel","燃料","The bus uses clean fuel.","这辆公交车使用清洁燃料。"],
      ["toxic","有毒的","Toxic waste must be treated.","有毒废物必须处理。"],
      ["hazardous","有害的","Hazardous materials need special care.","有害物质需要特殊处理。"],
      ["waste","废物","Reduce kitchen waste daily.","每天减少厨房垃圾。"],
      ["sewage","污水","Sewage flows into the river.","污水流入河流。"],
      ["irrigation","灌溉","The canal provides irrigation water.","这条运河提供灌溉用水。"],
      ["desertification","荒漠化","Desertification threatens farmland.","荒漠化威胁农田。"],
      ["monsoon","季风","The monsoon brings heavy rain.","季风带来大雨。"],
      ["typhoon","台风","The typhoon closed the port.","台风使港口关闭。"],
      ["hurricane","飓风","The hurricane damaged many homes.","飓风毁坏了许多房屋。"],
      ["blizzard","暴风雪","The blizzard stopped all traffic.","暴风雪使交通全部中断。"],
      ["heatwave","热浪","The heatwave broke records.","热浪打破了纪录。"],
      ["ozone","臭氧","The ozone layer is recovering.","臭氧层正在恢复。"],
      ["smog","雾霾","Smog covered the city for days.","雾霾笼罩城市数日。"],
      ["compost","堆肥","Kitchen scraps become compost.","厨房垃圾变成堆肥。"],
      ["reservoir","水库","The reservoir supplies the town.","水库为小镇供水。"],
      ["aquifer","含水层","The aquifer is drying up.","含水层正在干涸。"],
      ["wetland","湿地","Birds nest in the wetland.","鸟类在湿地筑巢。"],
      ["coral","珊瑚","Coral reefs support sea life.","珊瑚礁支撑着海洋生命。"],
      ["rainforest","雨林","The rainforest is home to millions.","雨林是数百万生物的家园。"],
      ["vegetation","植被","Thick vegetation covers the slope.","山坡上覆盖着茂密的植被。"],
      ["contamination","污染；沾染","Contamination made the water unsafe.","污染使水不再安全。"],
      ["purify","净化","Plants help purify the air.","植物有助于净化空气。"],
      ["conservationist","环保人士","The conservationist planted a thousand trees.","环保人士种了一千棵树。"],
      ["activist","活动人士","The activist led the clean-up.","活动人士组织了清理行动。"],
      ["legislation","法规","New legislation limits plastic use.","新法规限制塑料使用。"],
      ["protocol","议定书","Countries signed a climate protocol.","各国签署了气候议定书。"],
      ["accord","协议","The accord aims to cut pollution.","该协议旨在减少污染。"],
      ["pledge","承诺","Cities made a clean energy pledge.","多个城市作出了清洁能源承诺。"],
      ["mitigation","减缓","Mitigation reduces future damage.","减缓措施减少未来的损害。"],
      ["adaptation","适应","Adaptation helps communities cope.","适应帮助社区应对变化。"],
      ["resilience","韧性","Trees add resilience to coasts.","树木增强海岸的韧性。"],
      ["catastrophe","灾难","The oil spill was an ecological catastrophe.","石油泄漏是一场生态灾难。"]
    ]
  },
  {
    id: "news-world", name: "国际新闻", tag: "国际", desc: "冲突、援助、外交、国际组织等环球报道词汇",
    words: [
      ["global","全球的","Trade is now truly global.","贸易如今真正全球化了。"],
      ["international","国际的","The issue needs international cooperation.","这个问题需要国际合作。"],
      ["region","地区","The region saw heavy rainfall.","该地区降雨量大。"],
      ["conflict","冲突","The conflict lasted a decade.","冲突持续了十年。"],
      ["peace","和平","Everyone hopes for lasting peace.","人人都希望持久的和平。"],
      ["alliance","联盟","The alliance shares intelligence.","该联盟共享情报。"],
      ["border","边境","The border reopened at dawn.","边境在黎明时重新开放。"],
      ["refugee","难民","Refugees found shelter in the camp.","难民在营地找到了栖身之所。"],
      ["humanitarian","人道主义的","Aid groups gave humanitarian help.","援助组织提供了人道主义帮助。"],
      ["crisis","危机","The water crisis grew worse.","水危机加剧了。"],
      ["stability","稳定","Stability attracts foreign investment.","稳定吸引外国投资。"],
      ["negotiation","谈判","The negotiation lasted all week.","谈判持续了整整一周。"],
      ["coalition","联合；同盟","A coalition of nations acted together.","多国联盟共同行动。"],
      ["territory","领土","The army defended its territory.","军队保卫自己的领土。"],
      ["sovereignty","主权","Each state respects the other's sovereignty.","各国尊重彼此的主权。"],
      ["embassy","大使馆","The embassy issued travel advice.","大使馆发布了旅行建议。"],
      ["diplomat","外交官","The diplomat brokered the deal.","外交官促成了这项协议。"],
      ["sanction","制裁","Sanctions targeted the banking sector.","制裁针对银行业。"],
      ["resolution","决议","The council passed a resolution.","理事会通过了一项决议。"],
      ["summit","峰会","The summit ended with a joint statement.","峰会以联合声明结束。"],
      ["aid","援助","The country received food aid.","该国获得了粮食援助。"],
      ["relief","救济","Relief supplies reached the coast.","救济物资运抵沿海地区。"],
      ["famine","饥荒","Famine threatened the region.","饥荒威胁着该地区。"],
      ["earthquake","地震","The earthquake measured seven.","地震震级为七级。"],
      ["disaster","灾害","The flood was a national disaster.","洪水是一场全国性灾害。"],
      ["response","应对","The response was quick and organized.","应对迅速且有组织。"],
      ["cooperation","合作","Scientific cooperation crosses borders.","科学合作跨越国界。"],
      ["tension","紧张局势","Tension eased after the talks.","会谈后紧张局势缓和。"],
      ["confrontation","对抗","Both sides avoided confrontation.","双方都避免对抗。"],
      ["mediation","调停","Mediation brought the sides together.","调停让双方坐到一起。"],
      ["ceasefire","停火","The ceasefire held for months.","停火维持了数月。"],
      ["mission","使命；任务","The peace mission continues.","和平使命仍在继续。"],
      ["delegation","代表团","A trade delegation visited the capital.","一个贸易代表团访问了首都。"],
      ["charter","宪章","The charter protects basic rights.","宪章保护基本权利。"],
      ["protocol","议定书","The protocol sets the rules.","议定书规定了规则。"],
      ["treaty","条约","The treaty bans such weapons.","条约禁止这类武器。"],
      ["embargo","禁运","The embargo limited trade.","禁运限制了贸易。"],
      ["restriction","限制","The restriction eased this spring.","限制于今年春天放宽。"],
      ["visa","签证","Her visa was approved.","她的签证获批了。"],
      ["asylum","庇护","He asked for asylum abroad.","他在国外寻求庇护。"],
      ["citizenship","国籍；公民身份","She applied for citizenship.","她申请了公民身份。"],
      ["integration","融合","Integration helps new arrivals settle.","融合帮助新移民安顿下来。"],
      ["solidarity","团结","Workers showed solidarity across borders.","工人们跨越国界展现团结。"],
      ["dialogue","对话","The dialogue aims at trust.","对话旨在建立信任。"],
      ["reconciliation","和解","Reconciliation came after years.","多年之后达成了和解。"],
      ["demilitarize","非军事化","The zone was demilitarized.","该区域已实现非军事化。"],
      ["occupation","占领","The occupation ended long ago.","占领早已结束。"],
      ["liberation","解放","The day marks liberation.","这一天标志着解放。"],
      ["independence","独立","The nation celebrates independence.","这个国家庆祝独立。"],
      ["development","发展","The program funds rural development.","该项目资助农村发展。"],
      ["poverty","贫困","Education lifts people out of poverty.","教育帮助人们摆脱贫困。"],
      ["inequality","不平等","The report highlights income inequality.","报告突出了收入不平等。"],
      ["prosperity","繁荣","Trade brings shared prosperity.","贸易带来共同繁荣。"],
      ["infrastructure","基础设施","New roads improve infrastructure.","新道路改善了基础设施。"],
      ["democracy","民主","Free press supports democracy.","自由新闻支持民主。"],
      ["human-rights","人权","The court protects human-rights.","法院保护人权。"],
      ["tribunal","法庭","An international tribunal heard the case.","国际法庭审理了此案。"]
    ]
  },
  {
    id: "news-media", name: "报纸出版术语", tag: "报纸", desc: "看懂英文报纸版面和出版行业必备词",
    words: [
      ["newspaper","报纸","The newspaper arrives every morning.","报纸每天早上送达。"],
      ["daily","日报","The daily prints city news.","这份日报刊登本市新闻。"],
      ["weekly","周刊","The weekly reviews the latest films.","这份周刊点评最新电影。"],
      ["monthly","月刊","The monthly is a science journal.","这本月刊是一份科学期刊。"],
      ["edition","版本","The late edition hit the stands.","晚报版上市了。"],
      ["issue","期号","The first issue sold out.","创刊号售罄了。"],
      ["circulation","发行量","Circulation dropped this year.","今年发行量下降了。"],
      ["print","印刷","The book is still in print.","这本书仍在印刷发行。"],
      ["publish","出版","They publish children's books.","他们出版儿童书籍。"],
      ["publisher","出版社","The publisher rejected the draft.","出版社退回了稿件。"],
      ["journalist","记者","The journalist covered the trial.","这名记者报道了审判。"],
      ["columnist","专栏作家","The columnist writes on city life.","专栏作家写城市生活。"],
      ["editorial","社论","The editorial backed the reform.","社论支持这项改革。"],
      ["obituary","讣告","The obituary honored the artist.","讣告向这位艺术家致敬。"],
      ["advertisement","广告","The advertisement ran in the paper.","广告刊登在报纸上。"],
      ["classified","分类广告","He found the job in the classified ads.","他在分类广告中找到了这份工作。"],
      ["supplement","增刊","The supplement covers education.","增刊报道教育。"],
      ["magazine","杂志","The magazine comes out monthly.","这本杂志每月出版。"],
      ["tabloid","小报","The tabloid printed big photos.","小报刊登了大照片。"],
      ["broadsheet","大报","The broadsheet keeps a calm tone.","这份大报保持沉稳的基调。"],
      ["section","版面；栏目","Turn to the sports section.","翻到体育版。"],
      ["headline","标题","The headline says it all.","标题说明了一切。"],
      ["caption","图片说明","The caption names the people.","图片说明标注了人物姓名。"],
      ["byline","署名行","Her byline appears weekly.","她的署名每周出现。"],
      ["dateline","电头；日期栏","The dateline reads Beijing.","电头写着北京。"],
      ["correspondent","记者","The correspondent filed from the scene.","记者在现场发稿。"],
      ["freelancer","自由撰稿人","A freelancer sells stories to papers.","自由撰稿人向报纸出售稿件。"],
      ["archive","档案","The archive stores old copies.","档案中存放着过期的报纸。"],
      ["subscription","订阅","The subscription auto-renews.","订阅会自动续费。"],
      ["readership","读者群","The paper has a young readership.","这份报纸的读者群偏年轻。"],
      ["printing","印刷术","Printing made books affordable.","印刷术让书籍变得便宜。"],
      ["layout","版面设计","The layout guides the reader's eye.","版面设计引导读者视线。"],
      ["typography","排印","Good typography aids reading.","良好的排印有助于阅读。"],
      ["press","新闻界","The press gathered at noon.","记者们在中午聚集。"],
      ["wire","通讯社电讯","The wire sent the alert at once.","通讯社立即发出警报。"],
      ["agency","通讯社","The agency feeds news to stations.","通讯社向各台供稿。"],
      ["dispatch","快讯","A dispatch arrived from abroad.","一份快讯从国外发来。"],
      ["exclusive","独家","The paper printed an exclusive.","这家报纸刊登了独家报道。"],
      ["leak","泄密","The leak came from inside.","泄密来自内部。"],
      ["embargo","新闻禁令","The report was under embargo until noon.","这份报道在中午前受新闻禁令限制。"],
      ["deadline","截稿时间","The deadline is five o'clock.","截稿时间是五点。"],
      ["plagiarism","抄袭","The paper fired him for plagiarism.","报社因抄袭解雇了他。"],
      ["check","核对；核查","Check the spelling twice.","仔细核对两遍拼写。"],
      ["accuracy","准确性","Accuracy builds reader trust.","准确性赢得读者信任。"],
      ["objectivity","客观性","The news kept full objectivity.","新闻保持了完全的客观。"],
      ["fairness","公正","Fairness guides every story.","公正指导每一篇报道。"],
      ["integrity","诚信","The editor's integrity is known.","这位编辑的诚信众所周知。"],
      ["reputation","声誉","The paper guards its reputation.","这家报纸维护自己的声誉。"],
      ["credibility","公信力","Facts build credibility.","事实建立公信力。"],
      ["fact-checker","事实核查员","A fact-checker reviews each claim.","事实核查员审查每一条说法。"],
      ["scoop","独家报道","The scoop made front pages everywhere.","这则独家报道登上了各处头版。"],
      ["interview","访谈","The interview aired this morning.","这段访谈今早播出。"],
      ["feature","特稿","The feature profiles a local chef.","特稿介绍了一位本地厨师。"],
      ["review","书评；影评","The review gave three stars.","书评给了三星。"],
      ["column","专栏","Her column runs on Mondays.","她的专栏每周一刊登。"],
      ["opinion","观点","The opinion page invites letters.","观点版欢迎读者来信。"],
      ["letters","读者来信","Letters to the editor fill the page.","读者来信占满了版面。"],
      ["notice","启事","The notice announced a new opening.","启事宣布了一个新的开业信息。"],
      ["index","索引","The index lists every topic.","索引列出了所有主题。"],
      ["volume","卷；册","Volume two covers the war years.","第二卷讲述战争年代。"],
      ["binding","装订","The binding is strong leather.","装订是坚固的皮革。"],
      ["paperback","平装本","The paperback costs less.","平装本更便宜。"],
      ["hardcover","精装本","The hardcover sits on the shelf.","精装本摆在书架上。"]
    ]
  }
]};
